### ISSUE TITLE
Introduction to Developing Skills:  vocab directory and defining Intents needs more detail

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/docs-rewrite#28]
"vocab directory and defining Intents" section needs more detail. Particularly: the current example shows the simplest case of single-vocab-element/phrase. Notably missing is a little explanation about the intent handlers' chaining of the "require" method and how that relates to the vocab files. And also importantly: assuming this permits some word or words not specified by a vocab file to appear in between vocab elements, what words are allowed there? what words _reliably_ can appear there? Only articles? Any word, as long as less than 3 of them? or any word as long as they don't collide with other intents?

**Comment by KathyReid** [comment]
Need to chat this one over with @penrods. Will flag.

**Comment by KathyReid** [comment]
This is _possibly_ covered by
https://github.com/MycroftAI/docs-rewrite/pull/42

**Comment by KathyReid** [comment]
Closed by #42
