### ISSUE TITLE
Broken link on page: Introduction to Developing Skills

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/docs-rewrite#30]
On page:  https://mycroft.ai/documentation/skills/introduction-developing-skills/#prerequisites
there is a hyperlink labeled: "Mycroft for Linux" that points to URL:  https://mycroft.ai/documentation/skills/introduction-developing-skills/Mycroft-for-Linux.md  which appears to not exist, so following the link gives a 404 error.

**Comment by KathyReid** [comment]
Thanks @jrwarwick for flagging this and raising an issue, I really appreciate it.
