### ISSUE TITLE
Submit a PR (Pull Request) in GitHub to have your Skill listed - bullet list refinements

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/docs-rewrite#48]
[Submit a PR (Pull Request) in GitHub to have your Skill listed](https://mycroft.ai/documentation/skills/skill-submission/#submit-a-pr-pull-request-in-github-to-have-your-skill-listed) has a few opportunities for improvement:
 - third bullet:
  "You will need to choose **with** repositories to compare and create a PR from"
  probably should be:
  "You will need to choose **which** repositories to compare and create a PR from"
 - Fourth bullet includes some code-sample/mono-space text. I think it would look better if indented to 
  appear to be "child" content of the bullet
 - And then, consider making this last line a fifth bullet:
  "Fill in the PR template and submit your PR."

Also, if outstanding issue MycroftAI/mycroft-skills#274 is confirmed and addressed, the template example text in fourth bullet should be updated.

**Comment by KathyReid** [comment]
Thanks @jrwarwick for the pickup, I have updated this except for the README.md update; will tackle that separately.
