### ISSUE TITLE
Generate a README.md file for your Skill - typos

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/docs-rewrite#49]
"relevant" would be a better word than "relative" in this paragraph:   [Generate a README.md file for your Skill](https://mycroft.ai/documentation/skills/skill-submission/#generate-a-readme-md-file-for-your-skill)

In the paragraph following, "the" instead of "this" preceding plural "sections"

**Comment by KathyReid** [comment]
Great pickup, thank you @jrwarwick. 
Resolved.
