### ISSUE TITLE
Introduction-developing-skills broken internal link

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/docs-rewrite#60]
The link labled "Simplifying your Skill code with intent_handler decorators" at the top of the [Developing a new skill page](https://mycroft.ai/documentation/skills/introduction-developing-skills/)
contains a URL anchor that is incorrect. Destination href:
https://mycroft.ai/documentation/skills/introduction-developing-skills/#simplifying-your-skill-code-with-intent_handler-_decorators_

is invalid. probably those underscores are formatting that leaked into href. There does exist this anchor:
"#simplifying-your-skill-code-with-intent_handler-decorators" which is surely what should have been in the href attribute.

**Comment by jrwarwick** [comment]
Actually it looks like there may be several internal anchor links broken in a variety of ways. Here is a second case:   view-source:https://mycroft.ai/documentation/skills/skill-settings/#settingsjson but the real anchor is #settings-json   (with an hyphen in the middle).

**Comment by KathyReid** [comment]
Way behind on triaging / closing some of these, apologies. 
Internal links updated. 
https://validator.w3.org/checklink?uri=https%3A%2F%2Fmycroft.ai%2Fdocumentation%2Fskills%2Fintroduction-developing-skills%2F&hide_type=all&depth=&check=Check

Closing issue.
