### ISSUE TITLE
Make a new repo using the Template Skill - missing separator or line break in commandlines

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/docs-rewrite#63]
In section [Make a new repo using the Template Skill]  (https://mycroft.ai/documentation/skills/introduction-developing-skills/#make-a-new-repo-using-the-template-skill ) there is an incorrect commandline:

> $ cp -R 00__skill_template skill-hello-worldls -las

That should be broken into two commands:
`$ cp -R 00__skill_template skill-hello-world`
`$ ls -las`

or else perhaps
`$ cp -R 00__skill_template skill-hello-world  ;  ls -las`

This was discovered by new developer ragesoss (from Mattermost)

**Comment by KathyReid** [comment]
Thanks so much for reporting this @jrwarwick, I've resolved this now. 
I also fixed a couple of broken fragments that `toc-markdown` didn't generate correctly - it doesn't handle backticks ``` very well.
