### ISSUE TITLE
Wifi setup link to github is broken.

### ISSUE THREAD

**Issue by clebio** [MycroftAI/docs-rewrite#70]
On https://mycroft.ai/documentation/picroft/#downloading-the-disk-image, the sentence:

> If you’re concerned about privacy with Picroft’s WiFi setup, you can inspect our [Wifi Client code on GitHub](https://github.com/MycroftAI/mycroft-core/tree/dev/mycroft/client/wifisetup).
has a broken link: https://github.com/MycroftAI/mycroft-core/tree/dev/mycroft/client/wifisetup

I poked around a bit but haven't found the new, correct link.

**Comment by KathyReid** [comment]
Thanks @clebio for reporting this - really appreciate it. 
Fixed with correct link :+1:
